/* v13.36.0 Family profiles. Registration and account handoff are not yet enabled. */
function openFamilyPlayers(){
 document.getElementById('bxh-family-dialog')?.close();
 const uid=currentAuthUid(),epoch=engagementSessionEpoch,previous=document.activeElement,dialog=document.createElement('dialog');dialog.id='bxh-family-dialog';dialog.className='raffle-claim-dialog';
 dialog.innerHTML='<header><h2>家庭選手</h2><button class="btn btn-ghost" data-family="close">關閉</button></header><p class="hint">先建立孩子的獨立選手資料，不需另外申請登入帳號。代報名與長大後帳號移交尚未開放。</p><div data-family="list"></div><button class="btn btn-primary" data-family="new">新增孩子</button><form hidden><h3 data-family="heading"></h3><label>孩子姓名<input name="name" maxlength="40" required autocomplete="off"></label><label>暱稱（選填）<input name="nickname" maxlength="40" autocomplete="off"></label><label>出生日期<input name="birthDate" type="date" required></label><label data-family="guardian"><input name="guardianConfirmed" type="checkbox" style="width:auto"> 我是孩子的家長或監護人，確認資料正確。</label><p class="hint">姓名與生日只供本人管理；本階段不公開，也不會改變家長的報名或戰績。</p><button class="btn btn-primary" type="submit">儲存資料</button> <button class="btn btn-ghost" type="button" data-family="cancel">取消編輯</button></form><p data-family="status" role="status" aria-live="polite"></p><button class="btn btn-ghost" data-family="refresh">重新讀取</button>';
 const q=k=>dialog.querySelector('[data-family="'+k+'"]'),form=dialog.querySelector('form'),status=q('status');let profiles=[],revision=0,editing=null,busy=false,pending=null,closed=false;
 const valid=()=>!closed&&currentAuthUid()===uid&&engagementSessionEpoch===epoch;
 const errors={'duplicate-child':'這位孩子已存在，請查看現有或已封存資料。','invalid-name':'請填寫姓名，姓名及暱稱限40字。','invalid-birth-date':'請填寫正確的出生日期，不能晚於今天。','guardian-confirmation-required':'請確認你是孩子的家長或監護人。','version-conflict':'其他視窗已更新，請重新讀取後再編輯。','profile-limit':'最多保留20位使用中的家庭選手。','profile-transferred':'此選手已移交，不能再由原家長修改。','auth-required':'請重新登入。'};
 const close=()=>{if(closed)return;closed=true;clearInterval(timer);dialog.close();dialog.remove();previous?.focus?.();};const timer=setInterval(()=>{if(!valid())close();},500);
 function lock(v){busy=v;dialog.querySelectorAll('button,input').forEach(x=>{if(x!==q('close'))x.disabled=v;});}
 function list(){q('list').innerHTML=profiles.map(p=>`<article class="claim-history-row"><strong>${esc(p.name)}${p.nickname?'（'+esc(p.nickname)+'）':''}</strong><p>選手編號：${esc(p.playerId)}</p><p>生日：${esc(p.birthDate)}${p.archived?'｜已封存':''}</p><button class="btn btn-ghost" data-edit="${esc(p.id)}">編輯</button> <button class="btn btn-ghost" data-state="${esc(p.id)}">${p.archived?'恢復使用':'封存'}</button></article>`).join('')||'<p>尚未建立孩子的選手資料。</p>';q('list').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(profiles.find(p=>p.id===b.dataset.edit)));q('list').querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{const p=profiles.find(x=>x.id===b.dataset.state);if(confirm((p.archived?'恢復':'封存')+'「'+p.name+'」？選手編號與紀錄會保留。'))mutate({action:p.archived?'restore':'archive',id:p.id});});}
 async function request(data){const r=await window.engagementService.family(data);if(!valid())throw Error('auth-required');if(!r?.ok)throw Error('unavailable');return r;}
 function message(e){const s=String(e?.message||e);return Object.entries(errors).find(([k])=>s.includes(k))?.[1]||'連線結果尚未確認，請按「重試原操作」。';}
 async function load(){if(busy)return;lock(true);try{const r=await request({action:'list'});profiles=r.profiles;revision=r.revision;list();status.textContent='資料已讀取。';}catch(e){if(valid())status.textContent=message(e);}finally{if(valid())lock(false);}}
 function edit(p){if(busy||pending)return;editing=p||null;form.hidden=false;q('heading').textContent=p?'編輯家庭選手':'新增孩子';for(const k of ['name','nickname','birthDate'])form.elements[k].value=p?.[k]||'';form.elements.guardianConfirmed.checked=false;q('guardian').hidden=!!p;form.elements.guardianConfirmed.required=!p;form.elements.name.focus();}
 async function mutate(data){if(busy)return;if(pending&&data)return;pending=pending||{...data,revision,operationId:crypto.randomUUID()};lock(true);status.textContent='儲存中…';try{const r=await request(pending);profiles=r.profiles;revision=r.revision;pending=null;form.hidden=true;list();status.textContent='已儲存；代報名功能尚未開放。';q('refresh').textContent='重新讀取';}catch(e){if(valid()){status.textContent=message(e);const s=String(e?.message||e);if(Object.keys(errors).some(k=>s.includes(k))||s.includes('invalid-operation'))pending=null;q('refresh').textContent=pending?'重試原操作':'重新讀取';}}finally{if(valid()){lock(false);if(pending){q('new').disabled=true;form.querySelectorAll('button,input').forEach(x=>x.disabled=true);q('list').querySelectorAll('button').forEach(x=>x.disabled=true);}}}}
 form.onsubmit=e=>{e.preventDefault();mutate({action:editing?'update':'create',id:editing?.id,name:form.elements.name.value,nickname:form.elements.nickname.value,birthDate:form.elements.birthDate.value,guardianConfirmed:form.elements.guardianConfirmed.checked});};q('close').onclick=close;dialog.oncancel=e=>{e.preventDefault();close();};dialog.onclose=close;q('new').onclick=()=>edit(null);q('cancel').onclick=()=>{form.hidden=true;};q('refresh').onclick=()=>pending?mutate():load();document.body.appendChild(dialog);dialog.showModal();load();
}
