const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let now=0,seq=0,overlay,focused,removed=0,reduced=false;const timers=new Map(),listeners=new Map();
function el(){return {hidden:false,disabled:false,checked:false,textContent:'',classList:{add(){},remove(){}},setAttribute(){},removeAttribute(){},focus(){focused=this;document.activeElement=this;},closest(){return null;}};}
const original=el();original.isConnected=true;
const document={activeElement:original,fullscreenElement:null,body:{style:{overflow:'scroll'},appendChild(){}},addEventListener:(n,f)=>listeners.set(n,f),removeEventListener:n=>listeners.delete(n),createElement(){const nodes=new Map(),reels=[el(),el(),el()];overlay={...el(),innerHTML:'',remove(){removed++;},querySelector(s){if(!nodes.has(s))nodes.set(s,el());const n=nodes.get(s);if(s==='.bxh-winner')n.querySelectorAll=()=>[this.querySelector('.bxh-next'),this.querySelector('.bxh-hold'),this.querySelector('.bxh-winner-close')];return n;},querySelectorAll(s){return s==='.bxh-reel'?reels:[...nodes.values()];}};return overlay;}};
const box={document,URL,window:{matchMedia:()=>({matches:reduced})},setTimeout(fn,ms){const id=++seq;timers.set(id,{fn,at:now+ms});return id;},clearTimeout:id=>timers.delete(id)};
vm.createContext(box);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../raffle-replay.js'),'utf8'),box);
function advance(ms){const end=now+ms;while(true){const entry=[...timers].sort((a,b)=>a[1].at-b[1].at)[0];if(!entry||entry[1].at>end)break;now=entry[1].at;timers.delete(entry[0]);entry[1].fn();}now=end;}
const api=box.window.bxhRaffleReplay,detail={drawnAt:1,event:{title:'<img onerror=bad>',prizes:[]},winners:[{nickname:'甲<script>',playerId:'P1',prizeName:'陀螺'},{nickname:'乙',playerId:'P2',prizeName:'門票'}]};
api.open(detail);assert.equal(document.body.style.overflow,'hidden');assert(!overlay.innerHTML.includes('<img onerror=bad>'));assert.equal(overlay.querySelector('.bxh-event-title').textContent,detail.event.title);
advance(4099);assert.equal(overlay.querySelector('.bxh-winner').hidden,true);advance(1);assert.equal(overlay.querySelector('.bxh-winner-name').textContent,'甲<script>');assert.equal(overlay.querySelector('.bxh-winner').hidden,false);
advance(10000);assert.equal(overlay.querySelector('.bxh-winner-name').textContent,'甲<script>','manual replay stays on winner');
detail.winners[1].nickname='changed';overlay.querySelector('.bxh-next').onclick();overlay.querySelector('.bxh-next').onclick();advance(4100);assert.equal(overlay.querySelector('.bxh-winner-name').textContent,'乙','snapshot and double click cannot skip/rewrite result');overlay.querySelector('.bxh-next').onclick();assert.equal(timers.size,0);assert.equal(document.body.style.overflow,'scroll');assert.equal(focused,original);
api.open(detail);overlay.querySelector('.bxh-auto').checked=true;overlay.querySelector('.bxh-auto').onchange();advance(4100);overlay.querySelector('.bxh-hold').onclick();advance(6000);assert.equal(overlay.querySelector('.bxh-winner-name').textContent,'甲<script>','pause cancels next');overlay.querySelector('.bxh-hold').onclick();advance(9600);assert.equal(overlay.querySelector('.bxh-winner-name').textContent,'changed');api.close();assert.equal(listeners.size,0);
api.open(detail);const before=removed;api.open(detail);assert.equal(removed,before+1,'only one overlay');listeners.get('keydown')({key:'Escape',preventDefault(){}});advance(10000);assert.equal(timers.size,0);assert.equal(document.body.style.overflow,'scroll');
api.open({...detail,winners:[]});assert.equal(overlay.querySelector('.bxh-spin').disabled,true);assert.equal(timers.size,0);api.close();reduced=true;api.open(detail);advance(400);assert.equal(overlay.querySelector('.bxh-winner').hidden,false);api.close();
console.log('PASS fixed snapshot, sequential/manual/auto reveal, pause, double clicks, safe text, empty results, reduced motion, Escape, close cleanup, focus and scroll restoration');
