const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
let uid='admin',response,requests=[],tick,overlay,closed=false;
const saved=new Map(),listeners={},elements={'.raffle-slot':{},'.raffle-replay-progress':{},'.raffle-replay-close':{},'.raffle-fullscreen':{}};
const box={Date,URL,URLSearchParams,Object,crypto:require('node:crypto'),setTimeout:()=>{},setInterval:fn=>(tick=fn,1),clearInterval:()=>{},location:{search:''},sessionStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)},document:{addEventListener:(n,f)=>listeners[n]=f,createElement:()=>overlay={innerHTML:'',querySelector:s=>elements[s],requestFullscreen:()=>Promise.resolve(),remove:()=>closed=true},body:{appendChild:()=>{}}},currentAuthUid:()=>uid,engagementSessionEpoch:1,userProfile:{realName:'管理員'},appPhase:'player-center',playerActiveTab:'raffles',currentRole:'player',render:()=>{},esc:s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),mailboxDate:String,inventoryExpiry:s=>Date.parse(s+':00+08:00'),inventoryImage:()=>'',confirm:()=>true,prompt:()=> '原因',loadMailbox:async()=>{},inventoryState:null,window:{engagementService:{raffle:async p=>{requests.push({...p});if(response instanceof Error)throw response;return response||{ok:true,events:[],canCreate:true};}}}};
box.pendingLoginIntent=null;
vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../raffle-ui.js'),'utf8'),box);
const target=attrs=>({getAttribute:k=>attrs[k]??null});
(async()=>{
 const id='a'.repeat(64);saved.set('bxh.raffle.return',id);assert.equal(box.restoreRaffleIntent(),true);assert.equal(box.raffleContext().id,id);assert.equal(box.playerActiveTab,'raffles');assert.equal(saved.has('bxh.raffle.return'),false);
 let c=box.raffleContext();c.canCreate=true;await box.handleRaffle('raffle-new',target({}));c.draft.title='<img src=x onerror=alert(1)>';assert(box.renderRafflePage().includes('&lt;img'));assert(!box.renderRafflePage().includes('<img src=x'));
 await box.handleRaffle('raffle-add-prize',target({}));assert.equal(c.draft.prizes.length,2);await box.handleRaffle('raffle-remove-prize',target({'data-index':'1'}));assert.equal(c.draft.prizes.length,1);
 await box.handleRaffle('raffle-add-rule',target({'data-kind':'ticket'}));assert.equal(c.draft.conditions[0].mode,'hold');listeners.input({target:{getAttribute:k=>({'data-raffle-field':'title'})[k]??null,type:'text',value:'草稿保留'}});assert.equal(c.draft.title,'草稿保留');
 response=Error('network timeout');await box.raffleMutate({action:'draw',id,operationId:'operation_1'});assert.equal(c.pending.operationId,'operation_1');
 vm.runInContext('raffleState=null',box);c=box.raffleContext();assert.equal(c.pending.operationId,'operation_1');response={ok:true,events:[]};await box.handleRaffle('raffle-retry-pending',target({}));assert.equal(requests.filter(r=>r.action==='draw').length,2);assert.equal(c.pending,null);
 c.pending={action:'draw'};uid='other';box.engagementSessionEpoch=2;assert.equal(box.raffleContext().pending,null,'pending requests never cross accounts');
 const calls=requests.length;box.playRaffleReplay({drawnAt:123,event:{title:'活動'},winners:[{nickname:'甲',playerId:'P1',prizeName:'A'},{nickname:'乙',playerId:'P2',prizeName:'B'}]});assert(overlay.innerHTML.includes('紀錄回放'));for(let i=0;i<12;i++)tick();assert.equal(elements['.raffle-slot'].textContent,'甲（P1）');for(let i=0;i<30;i++)tick();assert.equal(elements['.raffle-slot'].textContent,'乙（P2）');assert.equal(requests.length,calls,'replay never calls draw');elements['.raffle-replay-close'].onclick();assert.equal(closed,true);
 uid='';box.engagementSessionEpoch=3;c=box.raffleContext();c.id=id;await box.handleRaffle('raffle-login',target({}));assert.equal(saved.get('bxh.raffle.return'),id);assert.equal(box.appPhase,'player-login');
 console.log('PASS raffle UI login return, prize/rule editing, draft/escaping, persistent retry, account isolation and sequential fixed-result replay');
})().catch(e=>{console.error(e);process.exitCode=1;});
