const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const helpers=html.slice(html.indexOf('const refereeSwappedViews ='),html.indexOf('const QD_PLAYER_ICON_SVG ='));
const handler=html.slice(html.indexOf('  if(action==="referee-swap-view"){'),html.indexOf('  if(action==="referee-set-scoring-mode"){'));
const match={id:'m1',a:{playerId:'A'},b:{playerId:'B'},scoreA:3,scoreB:2,winnerId:null,log:[{side:'A',type:'extreme'}]};
const state={id:'room1',matches:[match],meta:{}};const before=JSON.stringify(state);
let renders=0;const ctx={state,getMatch:id=>id==='m1'?match:null,target:{getAttribute:()=> 'm1'},action:'referee-swap-view',esc:s=>s,renderPreservingScroll:()=>{renders++}};
vm.createContext(ctx);vm.runInContext(helpers+'\nfunction run(){'+handler+'}',ctx);
assert.equal(ctx.refereeViewClass(match),'');ctx.run();assert.equal(ctx.refereeViewClass(match),' swapped');
assert.equal(JSON.stringify(state),before);assert.equal(renders,1);ctx.run();assert.equal(ctx.refereeViewClass(match),'');
state.id='room2';assert.equal(ctx.refereeViewClass(match),'');
console.log('PASS referee swap changes presentation only; player IDs, scores, result and log stay identical');
ctx.esc=s=>String(s||'');ctx.playerName=id=>'Player-'+id;ctx.checkWinnerSide=m=>m.scoreA>=4?'A':m.scoreB>=4?'B':null;ctx.refereeStageLabel=()=> 'Final';ctx.WINNER_CROWN_SVG='';
vm.runInContext(html.slice(html.indexOf('function renderModal(){'),html.indexOf('function openModal(')),ctx);
match.scoreA=4;ctx.pendingModal={type:'confirm-result',matchId:'m1'};
let modal=ctx.renderModal();assert(modal.includes('Player-A'));assert(!modal.includes('Player-B'));assert(modal.includes('result-confirm-actions'));
ctx.pendingModal={type:'confirm-quick',matchId:'m1',selectedWinnerId:'B'};
modal=ctx.renderModal();assert(modal.includes('Player-B'));assert(!modal.includes('Player-A'));
console.log('PASS standard and quick result confirmations show only the selected winner');
